# Generated by Django 5.0.7 on 2024-08-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Volvo', 'Volvo')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('pover', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
